# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrionEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name=b'Entity Name')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name=b'created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name=b'updated on')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='OrionServicePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Entity Name')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name=b'created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name=b'updated on')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='orion_exporter.OrionEntity', verbose_name=b'Entity')),
            ],
            options={
                'verbose_name': 'Service Path',
                'verbose_name_plural': 'Service Paths',
            },
        ),
    ]
