# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-27 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion_exporter', '0002_auto_20180904_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionentity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='orionentity',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Entity Name'),
        ),
        migrations.AlterField(
            model_name='orionentity',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='orionservicepath',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='orionservicepath',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='orion_exporter.OrionEntity', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='orionservicepath',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Service Path'),
        ),
        migrations.AlterField(
            model_name='orionservicepath',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='updated on'),
        ),
    ]
